{% set version = "0.6.0" %}
{% set sha256 = "0c7854018066f86027557b835f27ce00c9b02b119d8d" %}


package:
  name: gplas
  version: {{ version }}
 
source:
  url: https://gitlab.com/sirarredondo/gplas/-/archive/{{ version }}/gplas-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

requirements:
  host:
    - python >3.6,<3.7
    - pip
  run:
    - python >=3.6
    - snakemake >=5.5.4

about:
  home: https://gitlab.com/sirarredondo/gplas
  license: GPL3.0
  license_file: LICENSE
  summary: gplas is a tool to bin plasmid-predicted contigs based on sequence composition, coverage and assembly graph information. It extends the possibility of accurately binning predicted plasmid contigs into several discrete plasmid components.

test:
  commands:
    - bash gplas.sh -h
    - bash gplas.sh -i test/faecium_graph.gfa -c mlplasmids -s 'Enterococcus faecium' -n 'my_isolate'
